import java.awt.HeadlessException;
import java.util.Properties;

import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rikysamuel
 */
public class EmailClient extends javax.swing.JFrame { 
    // Sender's email ID needs to be mentioned
    String from = "rikz.samuel@gmail.com";
    final String username = "rikysamuel";//change accordingly
    final String password = "900911VF";//change accordingly
    
    // Recipient's email ID needs to be mentioned.
    private String to;
    
    //Mime message object
    private Message message;

    // Assuming you are sending email through relay.jangosmtp.net
    private String host = "relay.jangosmtp.net";
    
    private Properties props;
    private Session session;
    
    /**
     * Creates new form EmailClient
     */
    public EmailClient() {
        props = new Properties();
        init();
        initComponents();
    }
    
    public void init(){      
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.starttls.enable", "true");
      props.put("mail.smtp.host", host);
      props.put("mail.smtp.port", "25");

      // Get the Session object.
      session = Session.getInstance(props,
         new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
               return new PasswordAuthentication(username, password);
	   }
         });
    }
    
    public void send(){
        try {
           to = Recipient.getText();
           
	   // Create a default MimeMessage object.
	   message = new MimeMessage(session);
	
	   // Set From: header field of the header.
	   message.setFrom(new InternetAddress(from));
	
	   // Set To: header field of the header.
	   message.setRecipients(Message.RecipientType.TO,
               InternetAddress.parse(to));
	
	   // Set Subject: header field
	   message.setSubject(Subject.getText());
	
	   // Now set the actual message
	   message.setText(Body.getText());

      } catch (MessagingException e) {
         throw new RuntimeException(e);
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        MenuButton = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Compose = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Recipient = new javax.swing.JTextField();
        CC = new javax.swing.JTextField();
        Subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Body = new javax.swing.JTextArea();
        Cancel = new javax.swing.JButton();
        Send = new javax.swing.JButton();
        Inbox = new javax.swing.JPanel();
        Draft = new javax.swing.JPanel();
        Sent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Compose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("To:");
        Compose.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 50, 40, -1));

        jLabel2.setText("CC:");
        Compose.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 76, 30, -1));

        jLabel3.setText("Subject:");
        Compose.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 50, -1));
        Compose.add(Recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 47, 760, -1));
        Compose.add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 73, 760, -1));
        Compose.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 99, 760, -1));

        Body.setColumns(20);
        Body.setRows(5);
        jScrollPane1.setViewportView(Body);

        Compose.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, 820, 310));

        Cancel.setText("Cancel");
        Compose.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        Compose.add(Send, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("Compose Email", Compose);

        javax.swing.GroupLayout InboxLayout = new javax.swing.GroupLayout(Inbox);
        Inbox.setLayout(InboxLayout);
        InboxLayout.setHorizontalGroup(
            InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        InboxLayout.setVerticalGroup(
            InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Inbox", Inbox);

        javax.swing.GroupLayout DraftLayout = new javax.swing.GroupLayout(Draft);
        Draft.setLayout(DraftLayout);
        DraftLayout.setHorizontalGroup(
            DraftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        DraftLayout.setVerticalGroup(
            DraftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Draft", Draft);

        javax.swing.GroupLayout SentLayout = new javax.swing.GroupLayout(Sent);
        Sent.setLayout(SentLayout);
        SentLayout.setHorizontalGroup(
            SentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 865, Short.MAX_VALUE)
        );
        SentLayout.setVerticalGroup(
            SentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sent Email", Sent);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel4.setText("EMAIL CLIENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        try{
            send();
            // Send message
            Transport.send(message);
            JOptionPane.showMessageDialog(this, "Message sent successfully....", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (HeadlessException | MessagingException e){
            System.err.println(e);
        }
    }//GEN-LAST:event_SendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Body;
    private javax.swing.JTextField CC;
    private javax.swing.JButton Cancel;
    private javax.swing.JPanel Compose;
    private javax.swing.JPanel Draft;
    private javax.swing.JPanel Inbox;
    private javax.swing.ButtonGroup MenuButton;
    private javax.swing.JTextField Recipient;
    private javax.swing.JButton Send;
    private javax.swing.JPanel Sent;
    private javax.swing.JTextField Subject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
