import functions.CheckingMails;
import functions.SendEmail;
import java.awt.HeadlessException;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Collections;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rikysamuel
 */
public final class EmailClient extends javax.swing.JFrame { 
    String hostServer;
    String mailStoreType;
    String account;
    String accpass;
    
    DefaultTableModel model;
    SendEmail se;
    CheckingMails cm;
    /**
     * Creates new form EmailClient
     */
    public EmailClient() {
        se = new SendEmail();
        cm = new CheckingMails();
        setUpEnvironment();
        
        initComponents();
        addPopUpMenu();
        
        model = (DefaultTableModel) InboxContent.getModel();
    }
    
    public void setUpEnvironment(){
        // Sending email
        se.from = "rikz.samuel@gmail.com";
        se.username = "rikysamuel";//change accordingly
        se.password = "900911VF";//change accordingly
        se.host = "relay.jangosmtp.net";
        
        //Retrieve email
        cm.host = "imap.gmail.com";// change accordingly
        cm.storeType = "imap";
        cm.user = "rikysamueltan@gmail.com";// change accordingly
        cm.password = "Brigade_101";// change accordingly
    }

    public void fetchEmail(){
        cm.check();
        Collections.reverse(cm.emails);

        cm.emails.stream().forEach((email) -> {
            addInbox(email);
        });
    }
    
    public boolean send(){
        return se.send(Recipient.getText(), Subject.getText(), Body.getText());
    }
    
    public void addInbox(Object[] rowData){
        model.addRow(rowData);
    }
    
    private void addPopUpMenu(){
        //sets the popup menu so it will show
        addMouseListener(new MouseAdapter()
        {
            @Override
            public void mouseClicked(MouseEvent event) {
                Point point = event.getPoint();
                int column = InboxContent.columnAtPoint(point);

                JOptionPane.showMessageDialog(InboxContent, "Column header #" + column + " is clicked");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        MenuButton = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Compose = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Recipient = new javax.swing.JTextField();
        CC = new javax.swing.JTextField();
        Subject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Body = new javax.swing.JTextArea();
        Cancel = new javax.swing.JButton();
        Send = new javax.swing.JButton();
        Inbox = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InboxContent = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Draft = new javax.swing.JPanel();
        Sent = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Compose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("To:");
        Compose.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 50, 40, -1));

        jLabel2.setText("CC:");
        Compose.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 76, 30, -1));

        jLabel3.setText("Subject:");
        Compose.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 50, -1));
        Compose.add(Recipient, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 47, 760, -1));
        Compose.add(CC, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 73, 760, -1));
        Compose.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 99, 760, -1));

        Body.setColumns(20);
        Body.setRows(5);
        jScrollPane1.setViewportView(Body);

        Compose.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, 820, 310));

        Cancel.setText("Cancel");
        Compose.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        Send.setText("Send");
        Send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendActionPerformed(evt);
            }
        });
        Compose.add(Send, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("Compose Email", Compose);

        InboxContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "From", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(InboxContent);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Message Body");
        jTextArea1.setEnabled(false);
        jScrollPane3.setViewportView(jTextArea1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Subject");

        jLabel6.setText("From:");

        jLabel7.setText("Someone");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jButton1.setText("Sync");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InboxLayout = new javax.swing.GroupLayout(Inbox);
        Inbox.setLayout(InboxLayout);
        InboxLayout.setHorizontalGroup(
            InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addGroup(InboxLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        InboxLayout.setVerticalGroup(
            InboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InboxLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inbox", Inbox);

        javax.swing.GroupLayout DraftLayout = new javax.swing.GroupLayout(Draft);
        Draft.setLayout(DraftLayout);
        DraftLayout.setHorizontalGroup(
            DraftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );
        DraftLayout.setVerticalGroup(
            DraftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Draft", Draft);

        javax.swing.GroupLayout SentLayout = new javax.swing.GroupLayout(Sent);
        Sent.setLayout(SentLayout);
        SentLayout.setHorizontalGroup(
            SentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 919, Short.MAX_VALUE)
        );
        SentLayout.setVerticalGroup(
            SentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sent Email", Sent);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        jLabel4.setText("EMAIL CLIENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendActionPerformed
        try{
            if (send()){
                JOptionPane.showMessageDialog(this, "Message sent successfully....", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException e){
            System.err.println(e);
        }
    }//GEN-LAST:event_SendActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fetchEmail();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmailClient().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Body;
    private javax.swing.JTextField CC;
    private javax.swing.JButton Cancel;
    private javax.swing.JPanel Compose;
    private javax.swing.JPanel Draft;
    private javax.swing.JPanel Inbox;
    private javax.swing.JTable InboxContent;
    private javax.swing.ButtonGroup MenuButton;
    private javax.swing.JTextField Recipient;
    private javax.swing.JButton Send;
    private javax.swing.JPanel Sent;
    private javax.swing.JTextField Subject;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
