/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rikysamuel
 */
public class ReplyPanel extends javax.swing.JPanel {
    public String fromMail;
    public String replyToMail;
    public String toMail;
    public String subjectMail;
    public String sentMail;
    public String bodyMail;
    
    /**
     * Creates new form NewJPanel
     */
    public ReplyPanel() {
        initComponents();
    }
    
    void fillBlank(){
        From.setText(fromMail);
        Replyto.setText(replyToMail);
        to.setText(toMail);
        subject.setText(subjectMail);
        sent.setText(sentMail);
        body.setText(bodyMail);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Replyto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        to = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        subject = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sent = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        body = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("From:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));
        add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 324, -1));

        jLabel2.setText("Reply-to:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));
        add(Replyto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 324, -1));

        jLabel3.setText("To:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));
        add(to, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 324, -1));

        jLabel4.setText("Subject:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));
        add(subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 323, -1));

        jLabel5.setText("Sent:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 20));
        add(sent, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 323, -1));

        body.setColumns(20);
        body.setRows(5);
        jScrollPane1.setViewportView(body);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 406, 271));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField From;
    private javax.swing.JTextField Replyto;
    private javax.swing.JTextArea body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sent;
    private javax.swing.JTextField subject;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
